### PR TITLE
Adds CW Additional Feild

### LINKED ISSUE #2: Implementation of "spoiler_text" aka Content Warning
Hi there,

I am using this quite a lot now with my mastodon instance - and I would love CW warnings to be implemented - so if there are no objections I will see about putting in a pull request here shortly.

Cheers,

Jake

### PR DESCRIPTION
**Pull request by jakevis**
This will close #2 
I just tested this on my n8n instance (0.208.1) with the latest stable mastodon (4.0.2) and it seems to work as expected:

image

image

### CODE REVIEW

**Comment by jakevis** [comment]
@ETdoFresh just a ping on this one to see if your interested in adding this feature?

**Comment by benborges** [comment]
Would love to see this accepted !!

**Comment by ETdoFresh** [comment]
Accepted and moving entire repo over to an org. I'll go ahead and add you @jakevis as an owner of the repo as well.

**Comment by jakevis** [comment]
Perfect, thank you @ETdoFresh - and yes happy to help out (also will unpublish that fork)

**Comment by ETdoFresh** [comment]
Awesome, sorry for the delay! Been mad busy with other stuff, was hard for me to get myself in the right mindset to even look at the PR. But yeah, when I did, it was super easy. So thx for the help and thx for your willingness to support! Automate everything time! :)

**Comment by jakevis** [comment]
> Awesome, sorry for the delay! Been mad busy with other stuff, was hard for me to get myself in the right mindset to even look at the PR. But yeah, when I did, it was super easy. So thx for the help and thx for your willingness to support! Automate everything time! :)

I know the feeling - none the less thanks for your work and add here. My folk is unpublished and repo removed. If I have some time over the next day or so ill check through the API for any other options and preemptively get them added.

**Pull request merged**
